### ISSUE TITLE
Can not run the project in a docker container with error "Cannot find module connect-redis"

### ISSUE THREAD

**Issue by foreverpersist** [no5no6/questionnaire#2]
I tried to run your project in a docker container. However it doesn't work.

Error:

```
/app/questionnaire # node questionnaire
module.js:557
    throw err;
    ^

Error: Cannot find module 'connect-redis'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/questionnaire/questionnaire.js:6:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

Node version:
```
/app/questionnaire # node -v
v9.4.0
```

Npm version:
```
/app/questionnaire # npm -v
5.6.0
```

**Comment by no5no6** [comment]
I fixed it . Please update your project， `git pull`
